;; (if (eq system-type 'windows-nt')
;;   (progn
;;    (setq exec-path
;;       (list
;;        "c:\\msys64\\usr\\bin\\"
;;        "C:\\Program Files (x86)\\GnuWin32\\bin"
;;        "C:\\WINDOWS"
;;        "C:\\WINDOWS\\System32"
;;        "C:\\WINDOWS\\System32\\Wbem"
;;        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
;;        "C:\\mu\\bin64"
;;        "C:\\mu\\bin"
;;        "C:\\Micron Common"
;;        "C:\\Program Files (x86)\\Intel\\iCLS Client\\"
;;        "C:\\Program Files\\Intel\\iCLS Client\\"
;;        "C:\\MTApps\\perl\\5.12.2\\x32\\prod\\bin"
;;        ;; "C:\\Program Files\\Teradata\\Client\\15.10\\bin"
;;        ;; "C:\\Program Files (x86)\\Teradata\\Client\\15.10\\bin"
;;        ;; "C:\\ProgramData\\Oracle\\Java\\javapath"
;;        ;; "C:\\Program Files\\Haskell\\bin"
;;        ;; "C:\\HaskellPlatform\\7.10.2-a\\lib\\extralibs\\bin"
;;        ;; "C:\\HaskellPlatform\\7.10.2-a\\bin"
;;        "C:\\Windows\\CCM"
;;        "C:\\Anaconda"
;;        "C:\\Anaconda\\Scripts"
;;        "C:\\HaskellPlatform\\7.10.2-a\\mingw\\bin"
;;        "C:\\Program Files\\TortoiseSVN\\bin"
;;        ;; "C:\\Users\\mvezzoli\\My Applications\\emacs-24.5\\bin"
;;        "C:\\Program Files (x86)\\WinSCP\\"
;;        ;; "C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\"
;;        ;; "C:\\Program Files\\erl9.0\\bin"
;;        ;; "C:\\Program Files (x86)\\Elixir\\bin"
;;        ;; "C:\\WINDOWS\\system32\\config\\systemprofile\\.mix\\escripts"
;;        ;; "C:\\HaxeToolkit\\haxe\\"
;;        ;; "C:\\HaxeToolkit\\neko"
;;        "C:\\Program Files (x86)\\sbt\\bin"
;;        "C:\\Program Files\\Git\\cmd"
;;        "C:\\Program Files\\nodejs\\"
;;        "C:\\Program Files (x86)\\Yarn\\bin\\"
;;        "C:\\PostgreSQL\\pg10\\bin"
;;        "C:\\Program Files\\Ballerina\\ballerina-0.982.0\\\\bin"
;;        "C:\\PostgreSQL\\pg11\\bin"
;;        "C:\\Users\\mvezzoli\\AppData\\Local\\Mu\\bin"
;;        "C:\\Program Files\\PuTTY\\"
;;        ;; "C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL"
;;        ;; "C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL"
;;        ;; "C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT"
;;        ;; "C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT"
;;        ;; "C:\\Program Files\\Intel\\WiFi\\bin\\"
;;        ;; "C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\"
;;        ;; "C:\\Program Files (x86)\\Elm\\0.19\\bin"
;;        ;; "result"
;;        "C:\\Users\\mvezzoli\\.cargo\\bin"
;;        "C:\\Program Files (x86)\\Elm Platform\\0.18\\bin"
;;        "C:\\Users\\mvezzoli\\AppData\\Roaming\\local\\bin"
;;        "C:\\Users\\mvezzoli\\AppData\\Roaming\\cabal\\bin"
;;        "c:\\Program Files (x86)\\PuTTY\\"
;;        "C:\\Users\\mvezzoli\\My Applications\\Tcl\\bin"
;;        "C:\\Program Files (x86)\\CVSNT\\"
;;        "C:\\Program Files (x86)\\Java\\jre6\\bin"
;;        "C:\\Program Files\\R\\R-2.13.1\\bin\\i386"
;;        ;; "T:\\tmap"
;;        "C:\\Users\\mvezzoli\\My Applications\\MikTex\\miktex\\bin\\"
;;        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
;;        ))

;;    (setenv "PATH" (mapconcat #'identity exec-path path-separator))))
(setenv "EDITOR" "~/bin/emacsclient")
