(setq inhibit-splash-screen t)
(load-theme 'misterioso)
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(org-agenda-list)
(toggle-frame-fullscreen)
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)
(setq ring-bell-function 'ignore)
(show-paren-mode 1)
(setq-default indent-tabs-mode nil)
(fset 'yes-or-no-p 'y-or-n-p)
